# teminal colors
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# aliases
alias ll='ls -lh'
alias ks='ls'
alias du='du -h -d 1'
alias df='df -h'
alias la='ls -la'
alias ipconfig='ifconfig'

# Django aliases
alias sp='python manage.py shell_plus'
alias runserver='python manage.py runserver'
alias c='python manage.py celeryd -l INFO --autoreload -E'

# elastic search
alias es='/Users/alandgraf/Downloads/elasticsearch-1.1.1/bin/elasticsearch'


# git/hg branch name in PS1
alias glog='git log --graph --pretty=format:'\''%Cred%h%Creset-%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\''--abbrev-commit --date=relative'
function parse_git_branch {
git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/*[\t]\(.*\)/\ git\ \1/'
}
function parse_hg_branch {
hg branch 2> /dev/null | sed -e 's/\(.*\)/\ hg\ \1/'
}
# 32m = green, 00m returns to default color
PS1="$PS1\[\033[0;32m\]\$(parse_git_branch)\[\033[00m\] "

# git tab completion
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# vi command within shell
set -o vi

# AWS keys
export AWS_ACCESS_KEY_ID=''
export AWS_SECRET_ACCESS_KEY=''


# virtualenvwrapper
source /opt/boxen/env.sh

# path update
export PATH=$PATH:~/bin

# sublime text
export EDITOR='subl -w'

# ssh-add vpn keys